version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123
    ports:
      - 5672:5672
      - 8080:15672

  localstack:
    image: localstack/localstack-light
    ports:
      - 4566-4599:4566-4599
      - 8090:8090
    environment:
      - SERVICES=sqs,sns
      - PORT_WEB_UI=8090
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      
