version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123
    ports:
      - 5672:5672
      - 8080:15672

  elasticmq:
    image: roribio16/alpine-sqs
    ports:
      - 9324:9324
      - 9325:9325
